stock-app/stock_app/__init__.py
from flask import Flask, render_template

from stock_app.blueprints.home import home as home_bp
from stock_app.blueprints.stock import stock as stock_bp
from stock_app.config import configurations

def create_app(environment_name='dev'):
    app = Flask(__name__)
    app.config.from_object(configurations[environment_name])

    app.register_blueprint(home_bp)
    app.register_blueprint(stock_bp)

    if environment_name != "dev":
        @app.errorhandler(500)
        def handle_error(execption):
            return render_template('500.html'), 500

    return app

# FLASK_APP="stock_app:create_app('dev')" FLASK RUN

stock-app/stock_app/blueprints/home.py
from flask import Blueprint, render_template, redirect, request, url_for

home = Blueprint('home', __name__)

@home.route('/')
def index():
    return render_template('home/index.html')

@home.route('/lookup', methods=['POST'])
def lookup():
    return redirect(url_for('stock.view_stock', ticker=request.form["ticker"]))

stock-app/stock_app/blueprints/stock.py
from flask import Blueprint, render_template
from stock_app.stock_data import get_financials, get_price, eps_chart_url

stock = Blueprint('stock', __name__, url_prefix='/stocks')

@stock.route('/<string:ticker>/quote')
def view_stock(ticker):
    stock_price = get_price(ticker)
    return render_template('stock/stock_quote.html', ticker=ticker,
                           stock_price=stock_price)

@stock.route('/<string:ticker>/financials')
def financials(ticker):
    financial_data = get_financials(ticker)
    financial_data.sort(key=lambda quarter: quarter["date"])
    chart_url = eps_chart_url(financial_data)

    return render_template('stock/financials.html', ticker=ticker,
                           financials=financial_data, chart_url=chart_url)

stock-app/stock_app/templates/base_layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}View Stock Prices{% endblock %}
            - StockApp
        </title>

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    </head>
    <body>
       {% include 'navbar.html' %}
       <div class="container mt-3">
           {% block content %}{% endblock %}
       </div>
    </body>
</html>

stock-app/stock_app/templates/home/index.html
{% extends "base_layout.html" %}
{% block title %} Portfolio {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm">
            <h1>Welcome to StockApp</h1>

            <form class="form-inline" method="POST" action="{{ url_for('home.lookup') }}"">
                <input class="form-control mr-sm-2" type="input" name="ticker" placeholder="AAPL" aria-label="Lookup">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Lookup</button>
            </form>

        </div>
        <div class="col-sm">
            {% include 'shared/portfolio.html' %}
        </div>
    </div>
{% endblock %}

stock-app/stock_app/templates/macros.html
{% macro stock_quote_link(stock_ticker) %}
    <a href="{{ url_for('stock.view_stock', ticker=stock_ticker) }}">{{ stock_ticker }}</a>
{% endmacro %}

stock-app/stock_app/templates/navbar.html
<nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">Stock App</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.url_rule.endpoint == 'index' %} active {% endif %}">
            <a class="nav-link" href="{{ url_for('home.index') }}">Home</a>
        </li>
    </ul>


    <form class="form-inline" method="POST" action="{{ url_for('home.lookup') }}">
        <input class="form-control mr-sm-2" type="input" name="ticker" placeholder="AAPL" aria-label="Lookup">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Lookup</button>
    </form>
</nav>

stock-app/stock_app/templates/shared/portfolio.html
{% from "macros.html" import stock_quote_link %}

<h1> View your portfolio </h1>

<ul>
    {% for ticker in ['AAPL', 'NTAP', 'FB'] %}
        <li>{{ stock_quote_link(ticker) }}</a></li>
    {% endfor %}
</ul>

stock-app/templates/stock_quote.html
{% extends "base_layout.html" %}
{% block title %} {{ticker | upper}} {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <h1 class="mb-3">{{ ticker | upper }} </h1>
        <hr />
        <h2> Price: ${{ stock_price | round(2) }} </h2>
      </div>
      <div class="col-sm">
          {% include 'portfolio.html' %}
      </div>
    </div>
  </div>
{% endblock %}

stock-app/templates/stock_quote_simple.html
{% extends "base_layout.html" %}
{% block title %} {{ticker}} {% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <h1 class="mb-3"> {{ ticker }} </h1>
        <hr />
        <h2> Price: ${{ stock_price }} </h2>
      </div>
      <div class="col-sm">
          {% include 'portfolio.html' %}
      </div>
    </div>
  </div>
{% endblock %}